@extends('layouts.spAdmin')
@section('title', 'Superadmin - Gift of Hope')
@section('content')
@php
    $pages = ['dashboard' => ['YOUR COMMUNITY, AT A GLANCE', 'A little oversight. A bigger impact.', 'Keep your community, funding, and connected devices moving forward.'], 'accounts' => ['PEOPLE & PERMISSIONS', 'Account management', 'Find community members, create administrators, and manage access.'], 'settings' => ['PLATFORM CONTROLS', 'System settings', 'Manage scoring, request limits, and verification email settings.'], 'monitor' => ['CONNECTED & INFORMED', 'System monitor', 'An overview of device health, funding outcomes, and audit events.'], 'requests' => ['MAKE HOPE HAPPEN', 'Fund requests', 'Review administrator requests and make informed funding decisions.'], 'activity' => ['EVERY ACTION, ACCOUNTED FOR', 'Activity log', 'Follow account, configuration, and funding changes in one place.']];
@endphp
@foreach($pages as $key => [$eyebrow, $title, $description])
<section data-sa-page="{{ $key }}" @if($key !== 'dashboard') hidden @endif>
    <div class="sa-heading"><div><span class="sa-eyebrow">{{ $eyebrow }}</span><h1>{{ $title }}</h1><p>{{ $description }}</p></div>@if(in_array($key, ['dashboard', 'accounts']))<button class="sa-button" data-sa-create>＋ Create admin</button>@elseif($key === 'monitor')<span class="sa-badge gray">Sample snapshot · not live</span>@endif</div>
    @if($key === 'dashboard' || $key === 'monitor')
    <div class="sa-stats">
        <article class="sa-stat"><div class="sa-stat-top">Total accounts<span class="sa-stat-icon">♧</span></div><strong data-sa-account-total>6</strong><small data-sa-admin-total>2 administrators</small></article>
        <article class="sa-stat"><div class="sa-stat-top">Connected devices<span class="sa-stat-icon">◉</span></div><strong>3 <span style="font-size:14px;color:#87988d">/ 4</span></strong><small>1 device needs attention</small></article>
        <article class="sa-stat"><div class="sa-stat-top">Pending requests<span class="sa-stat-icon">₱</span></div><strong data-sa-pending>3</strong><small>Awaiting your review</small></article>
        <article class="sa-stat"><div class="sa-stat-top">Approval rate<span class="sa-stat-icon">↗</span></div><strong data-sa-rate>50%</strong><small>Of reviewed requests</small></article>
    </div>
    @endif
    @if($key === 'dashboard')
    <div class="sa-grid"><article class="sa-card"><div class="sa-card-head"><div><h2>Requests needing your attention</h2><p>A helping hand starts with a decision.</p></div><a class="sa-link" href="#requests">View all ↗</a></div><div class="sa-table-wrap"><table class="sa-table"><thead><tr><th>Administrator / purpose</th><th>Amount</th><th>Review</th></tr></thead><tbody data-sa-request-preview></tbody></table></div><div class="sa-section-footer">Sample requests · review actions are simulated</div></article><article class="sa-card"><div class="sa-card-head"><h2>AI scoring mechanics</h2><a class="sa-link" href="#settings">Manage ↗</a></div><div class="sa-card-body"><div data-sa-scores></div><div class="sa-note">Category scores help prioritize requests. Final decisions stay with your team.</div></div></article></div>
    <div class="sa-grid equal"><article class="sa-card"><div class="sa-card-head"><h2>Connected donation boxes</h2><a href="#monitor" class="sa-link">View monitor ↗</a></div><div class="sa-card-body" data-sa-devices></div></article><article class="sa-card"><div class="sa-card-head"><h2>Recent activity</h2><a href="#activity" class="sa-link">View log ↗</a></div><div class="sa-card-body" data-sa-recent></div></article></div>
    @elseif($key === 'accounts')
    <article class="sa-card"><div class="sa-card-head"><h2>Community accounts</h2><span class="sa-badge gray">Preview records</span></div><div class="sa-toolbar"><input type="search" data-sa-account-search placeholder="Search by name or email" aria-label="Search accounts"><select data-sa-role-filter aria-label="Filter account role"><option value="">All roles</option><option>Admin</option><option>User</option></select><select data-sa-status-filter aria-label="Filter account status"><option value="">All statuses</option><option>Enabled</option><option>Disabled</option></select></div><div class="sa-table-wrap"><table class="sa-table"><thead><tr><th>Account</th><th>Role</th><th>Access</th><th>Last activity</th><th>Action</th></tr></thead><tbody data-sa-accounts></tbody></table></div></article>
    @elseif($key === 'settings')
    <div class="sa-grid equal"><article class="sa-card"><div class="sa-card-head"><h2>AI scoring mechanics</h2><span class="sa-badge">Priority scores</span></div><form class="sa-card-body" data-sa-settings="scores"><p>Set a score from 0 to 100 for each category.</p><div class="sa-fields" style="margin-top:20px">@foreach(['Education' => 85, 'Food' => 75, 'Medical' => 95, 'Shelter' => 80] as $category => $score)<label class="sa-field">{{ $category }} score<input name="{{ $category }}" type="number" min="0" max="100" step="1" value="{{ $score }}" required></label>@endforeach</div><div class="sa-actions"><button class="sa-button">Review changes</button></div></form></article>
    <article class="sa-card"><div class="sa-card-head"><h2>Global fund request limit</h2><span class="sa-badge gray">Request interval</span></div><form class="sa-card-body" data-sa-settings="limit"><p>Minimum time between fund requests, as specified in your workflow.</p><div class="sa-note">Current limit: <strong data-sa-limit>93 days</strong></div><label class="sa-field" style="margin-top:20px">New interval (days)<input type="number" name="days" min="93" step="1" value="93" required><small>The interval must be greater than 92 days.</small></label><div class="sa-actions"><button class="sa-button">Review changes</button></div></form></article></div>
    <article class="sa-card"><div class="sa-card-head"><div><h2>Verification email settings</h2><p>Configure the sender used for verification codes and decision notices.</p></div><span class="sa-badge gray">Demo credentials only</span></div><form class="sa-card-body" data-sa-settings="email"><div class="sa-note" style="margin:0 0 20px">Current sender: <strong data-sa-email>notifications@example.test</strong> · App name: <strong data-sa-appname>Gift of Hope</strong>. Use sample values in this preview.</div><div class="sa-fields"><label class="sa-field">New sender email<input type="email" name="email" placeholder="notifications@example.test" autocomplete="off" required></label><label class="sa-field">New app password name<input name="appname" placeholder="Gift of Hope mail" maxlength="80" required></label><label class="sa-field full">New mail password<input type="password" name="password" autocomplete="new-password" minlength="8" required><small>Never displayed in logs or saved by this preview.</small></label></div><div class="sa-actions"><button class="sa-button">Review changes</button></div></form></article>
    @elseif($key === 'monitor')
    <div class="sa-grid equal"><article class="sa-card"><div class="sa-card-head"><h2>IoT devices</h2><span class="sa-badge gray">4 devices</span></div><div class="sa-card-body" data-sa-devices></div></article><article class="sa-card"><div class="sa-card-head"><h2>Funding outcomes</h2><a class="sa-link" href="#requests">Review requests ↗</a></div><div class="sa-card-body"><div class="sa-big-number" data-sa-approved-amount>₱25,000</div><p>Total approved in sample requests</p><div class="sa-outcomes"><span><b data-sa-approved>1</b>Approved</span><span><b data-sa-denied>1</b>Denied</span><span><b data-sa-pending>3</b>Pending</span></div><progress data-sa-outcome-progress max="100" value="50" aria-label="Approval percentage"></progress><div class="sa-note">Approval percentage excludes requests awaiting review.</div></div></article></div>
    <article class="sa-card"><div class="sa-card-head"><h2>Audit events</h2><span class="sa-badge gray">Updates with preview actions</span></div><div class="sa-card-body" data-sa-audit></div></article>
    @elseif($key === 'requests')
    <article class="sa-card"><div class="sa-card-head"><h2>Administrator fund requests</h2><span class="sa-badge amber"><span data-sa-pending>3</span>&nbsp; pending</span></div><div class="sa-toolbar"><input type="search" data-sa-request-search placeholder="Search request, administrator, or category" aria-label="Search fund requests"><select data-sa-request-filter aria-label="Filter request status"><option value="">All statuses</option><option>Pending</option><option>Approved</option><option>Denied</option></select></div><div class="sa-table-wrap"><table class="sa-table"><thead><tr><th>Request / administrator</th><th>Category</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody data-sa-requests></tbody></table></div></article>
    @elseif($key === 'activity')
    <article class="sa-card"><div class="sa-card-head"><h2>Workspace activity</h2><span class="sa-badge gray">This preview session</span></div><div class="sa-toolbar"><input type="search" data-sa-log-search placeholder="Search actions or accounts" aria-label="Search activity log"></div><div class="sa-table-wrap"><table class="sa-table"><thead><tr><th>Action</th><th>Actor</th><th>Timestamp</th><th>Source</th></tr></thead><tbody data-sa-logs></tbody></table></div></article>
    @endif
</section>
@endforeach
@endsection
